### ISSUE TITLE
Method to clear a registered service

### ISSUE THREAD

**Issue by sahilthakral23** [young-steveo/bottlejs#108]
Is there a reason that the library does not have a method to clear a registered service? Actually while writing unit tests for my code I need to clear the original registration of service and register my mock service.

**Comment by young-steveo** [comment]
See [`resetProviders`](https://github.com/young-steveo/bottlejs#resetprovidersnames).  This will reset the provider for a service, so that the next time the service is requested it will be re-instantiated.  This will work for scenarios where you have registered a mock service, a test has fulfilled that mock's expectations, and now you want a new mock to be created for subsequent tests that share the same bottle container.  Note that the original provider that you registered will be used to create the subsequent service, so there's no need to re-register a service after you have reset the provider.

If you want to replace a registered service with a completely different service, it's better to use a new bottle instance.  If you are using named instances, you can use [`clear`](https://github.com/young-steveo/bottlejs#clearname) to reset the internal cache and get a new bottle with the same name.

**Comment by sahilthakral23** [comment]
Thanks @young-steveo  for the help. This does solve my problem. I somehow missed it in the documentation.
