### ISSUE TITLE
How do you handle interdependency?

### ISSUE THREAD

**Issue by jose-nunez** [young-steveo/bottlejs#111]
Hi,
Is it possible to hold 2 modules that implement a bunch of functions, where they call to each other? Something like:

```javascript
class A{
  constructor(b){
    this.b = b
  }
  getB(){
    return this.b.get()
  }
  get(){
    return 'this is A'
  }
}

class B{
  constructor(a){
    this.a = a
  }
  getA(){
    return this.a.get()
  }
  get(){
    return 'this is B'
  }
}
bottle.service('A',A,'B')
bottle.service('B',B,'A')
```

**Comment by young-steveo** [comment]
This is the classic [Circular Dependency](https://en.wikipedia.org/wiki/Circular_dependency) problem.  I think the best solution here is to create a third dependency that encapsulates the shared logic:

```javascript
class A {
  constructor(c){
    this.c = c
  }
  get(){
    return this.c.get()
  }
}

class B{
  constructor(c){
    this.c = c
  }
  get(){
    return this.c.get()
  }
}

class C{
  get() {
    return 'get'
  }
}
bottle.service('A',A,'C')
bottle.service('B',B,'C')
```

**Comment by young-steveo** [comment]
This is the classic [Circular Dependency](https://en.wikipedia.org/wiki/Circular_dependency) problem.  I think the best solution here is to create a third dependency that encapsulates the shared logic:

```javascript
class A {
  constructor(c){
    this.c = c
  }
  get(){
    return this.c.get()
  }
}

class B{
  constructor(c){
    this.c = c
  }
  get(){
    return this.c.get()
  }
}

class C{
  get() {
    return 'get'
  }
}
bottle.service('A',A,'C')
bottle.service('B',B,'C')
bottle.service('C',C)
```

This will typically make your program easier to understand, and keep everything as a dependency.  However, if that doesn't work for your particular use-case, or makes your logic more difficult to understand or maintain, you can also use bottle as a service locator.  I don't normally reccomend this approach because it's not as testable and your classes must be aware of bottle, but this is javascript and there's nothing stopping you:

```js
class A{
  constructor(b){
    this.b = b
  }
  getB(){
    return this.b.get()
  }
  get(){
    return 'this is A'
  }
}

class B{
  constructor(){
    this.a = bottle.container.A // sauce
  }
  getA(){
    return this.a.get()
  }
  get(){
    return 'this is B'
  }
}
bottle.service('A',A,'B')
bottle.service('B',B)
```
