### ISSUE TITLE
Typescript questions

### ISSUE THREAD

**Issue by tagyoureit** [young-steveo/bottlejs#124]
I'm migrating my project to use Typescript and have a couple of questions.  Hoping that someone will be able to help me.  :)  I'm just learning TS so appreciate any help.

Here is generally how my current (pre-Typescript project) is setup.  (I can see the Typescript definitions from bottle.d.ts.)

```
// app.js
var Bottle = require('bottlejs')
var bottle = Bottle.pop('poolController-Bottle');
bottle.factory('settings', require(__dirname + '/../etc/settings.js'))

// settings.js
module.exports = function (container) {

  var myFunction() {
    // some code
  }

  return {
      myFunction:  my Function
   }
}

// other files
container.settings.myFunction() // returns stuff
```

With Typescript, it requires (pun intended??) that the modules use the `import` syntax ([docs](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html)).  I have this working like:

```
// app.js
import * as Bottle from 'bottlejs';
const bottle = Bottle.pop('poolController-Bottle');

import _settings from '../etc/settings'
bottle.factory( 'settings', () => { return _settings(bottle.container) } )

// settings.js
export default function(container: Bottle.IContainer) {
   var myFunction() {
    // some code
  }

  return {
      myFunction:  my Function
   }
}

// other files
container.settings.myFunction() // returns stuff
```  

Here are my questions:
1.  Is this the best way to convert over to Typescript?  I realize that the 'lazy loading' will not work anymore because import statements can't exist inside functions.  I'm okay with this (unless there is a better way).

2. The calls to `container.settings.myFunction()` do work but in my editor (currently VS Code) but the Intellisense (Typescript code completion) isn't working (not showing up).  `container.` shows the internal methods of BottleJS but not the Services (and their respective methods).  Any thoughts here?  Is this just a function of using dependency injection or can/should I be able to get this working?

much thanks!

**Comment by young-steveo** [comment]
1. Unfortunately I can't say whether this is "good" Typescript or using best practices.  I am familiar with TypeScript's concepts but I don't use the language.  The TypeScript definition file was added by the bottlejs community.  On the other hand, it seems like it works, so I wouldn't sweat it too much.  Your application code is more important than the bottlejs stuff.  If it feels maintainable, I'd call it good.
2. VS Code can't code complete from the container because the container doesn't have your services actually defined until runtime. Check the provider code here: https://github.com/young-steveo/bottlejs/blob/master/src/Bottle/provider.js#L39-L69  When you access `container.something` at runtime for the first time, Bottle is using Javascript Object getters to lookup the service, instantiate it and attach it to the container.  For subsequent property lookups of the same service, bottle replaces the getter with the located service for performance.

If you want to take advantage of code completion and get bottle out of the way, you'll need to inverse everything and not use bottlejs as a service locator.  Your application code should not be aware that bottlejs is even a thing.  i.e. you would write code like:

```js
// a.js
export default function(b) {
    this.run = () => { /* etc. */ };
}
```

```js
// b.js
export default function() { }
```

And then orchestrate them with bottlejs from a single entrypoint in your app where all things are registered and then the "main" function is invoked:

```js
// index.js
import * as a from 'a';
import * as b from 'b';
bottle.service('a', a, 'b');
bottle.service('b', b);

bottle.container.a.run();
```

The above is really simple, and would be unwieldy with too many objects, but bottle also has some additional helpers to make this easier like [`bottle.register`](https://github.com/young-steveo/bottlejs#registerobj).  Using that your could read all files in a directory, loop over them and register them, and then invoke the main function.

The point being that the "application" code should not know that bottlejs exists, i.e. the application code should not be using bottle to find or load anything.  This separation of concerns will surely make your code more maintainable / mobile (e.g. you could more easily swap out the DI container that you use (not that I'm advocating for that, of course 😉  ))

**Comment by tagyoureit** [comment]
Thanks for the write-up.  I'll try to find some time this week to see if I can implement this.

**Comment by kernwig** [comment]
I know this issue is old and closed, but should someone else find there way here you can consider using [@sailplane/injector](https://docs.onica.com/projects/sailplane/en/latest/injector.html). It's a Typescript wrapper for bottlejs.
