### ISSUE TITLE
Classic object factory?

### ISSUE THREAD

**Issue by 486** [young-steveo/bottlejs#15]
If I am not mistaken, everything Bottle can inject are singletons.
What do you think about having an object factory where injecting a dependency constructs a new object of that type?

```
// Define MyClass

function MyClass(depA, depB) {
  this.depA = depA;
  this.depB = depB;
}

MyClass.prototype.doSomething = function doSomething() {
   this.depA.doSomethingElse();
}


// register MyClass

bottle.create("newInstance", MyClass, "depA", "depB");


// returns new MyClass(depA, depB) on every lookup of "newInstance"
// if depB had been registered with bottle.create(), a new instance of depB would be injected

var aNewInstance = bottle.container.newInstance
```

**Comment by seydu** [comment]
Here a Pimple user. I was expecting something like what @486 suggests. By default Pimple creates a new instance each time a service is requested unless you tell it to create a shared service.

**Comment by young-steveo** [comment]
@seydu I understand the potential of this idea&mdash;there was a time that I planned to add it to bottle.  However, I soon realized that the feature would facilitate a particularly confusing, counterintuitive pattern.  Take this code, for example:

```js
// typical service that is a singleton
bottle.service('Singleton', function SingletonConstructor() { });

// hypothetical new method `create` that will create a new instance every time
bottle.create('Thing', function ThingConstructor() {});

// Set some properties on some objects.  Typical javascript code:
bottle.container.Singleton.test = true;
bottle.container.Thing.test = true;

if (bottle.container.Singleton.test) {
  console.log('This works');
}

if (bottle.container.Thing.test) {
  console.log('This does not work, because Thing here is a new instance');
}
```

The new `create` method breaks javascript's object continuity.  Javascript objects are passed by copy of reference; when I access an object property and modify it's value in one part of my code, there is usually an expectation that it changes the contents of the object reference, since that's how Javascript objects work.

It's a problem of implicit/explicit design.  When I look at `bottle.container.Thing` from the perspective of user-land code, I would have no way of knowing if it was a new `Thing` or if it was the same `Thing` unless I knew the system or I looked up where `Thing` was registered on the DI container to see if `service` or `create` was used.

I hope that clears up my position on it. :smile:

**Comment by seydu** [comment]
I see what you mean. Thank for this detailed answer.

**Comment by young-steveo** [comment]
:+1: :cool:

**Comment by young-steveo** [comment]
@486 @seydu [Version 1.4.0](https://github.com/young-steveo/bottlejs/releases/tag/v1.4.0) now has a version of this functionality that works without the confusion I've outlined above.  Take a look at the docs for `instanceFactory`
