### ISSUE TITLE
Current object in tree rather than container is returned as first argument in factory

### ISSUE THREAD

**Issue by ConneXNL** [young-steveo/bottlejs#63]
So I am facing the following problem which I don't think is intended:

```
bottlejs.factory('a.tree.like.structure', (container) => {
    // container = bottlejs.container.a.tree.like rather than bottlejs.container
});
```

**Comment by young-steveo** [comment]
Hi, thanks for the report; that's an interesting problem to solve.

The reason you are getting the `bottlejs.container.a.tree.like` container is intentional.

I added namespaces to reduce collisions when sharing components between projects.  I like that these isolated components refer to their internal dependencies locally.  A typical use-case would be a vendor name prefix; the factory code could then be written like so:

```js
bottle.service('AwesomeComponent.ThingOne', function ThingOne() {});
bottle.factory('AwesomeComponent.ThingTwo', function ThingTwoFactory(container) {
    let ThingOne = container.ThingOne; // ThingOne from the AwesomeComponent namespace.
});
```

The internals of `AwesomeComponent` are isolated.

However, now that bottlejs is in the wild, I have seen several cases where the dot notation is used internally for code organization.  It's clear now that isolation is not desirable when doing something like this:

```js
bottle.service('Utility.Helpers', function Helpers() {});
bottle.factory('Entity.Thing', function ThingFactory(container) {
    // below are undefined because container is different
    container.Helpers; // undefined
    container.Utility.Helpers; // undefined
});
```
Now, I *could* pass a root container to every factory; in this case the `ThingFactory` code above could access the `Helpers` service by referring to the fully qualified namespace:

```js
let Helpers = container.Utility.Helpers;
```

But that's a bit too backwards incompatible with the current implementation for my taste.

Another solution could be to add a `$root` property to every container that points to the top-most root container.  This would allow the factory above to access the `Helpers` service like so:

```js
let Helpers = container.$root.Utility.Helpers;
```

I'm open to other suggestions.

**Comment by ConneXNL** [comment]
I indeed use the dot syntax to structure the container rather than namespacing to avoid name collision.

You can still use bottlejs.container from within the factory right? At least that's what I've been doing.

In that case this doesn't need fixing at the cost of BC. Maybe add the root container as the second argument?

I do think the docs needs fixing as I think everyone interprets it as getting the container (root container).

**Comment by young-steveo** [comment]
Yes, you can always reference the parent bottle instance container as you've suggested.  In fact, I'm starting to lean towards not providing access to the root container explicitly, since this would allow for accidental noisy neighbors--reducing the isolation currently enforced.

At least for now I will update the docs for the upcoming release.
