### ISSUE TITLE
Bottle.config.strict = true

### ISSUE THREAD

**Issue by akond** [young-steveo/bottlejs#68]
This code does not give me any exceptions, as I would expect. Is not strict option for this very purpose?

```
Bottle.config = {
	strict: true
}

let bottle = new Bottle();
let wth = bottle.container.giveMeException;

```

**Comment by young-steveo** [comment]
@akond The strict config was originally designed to detect undefined dependencies that are *injected* into your services, e.g.:

```js
Bottle.config = { strict : true };
let bottle = new Bottle();

let Thing = function(missing) { };
bottle.service('Thing', Thing, 'giveMeException'); // <-- still no throw

// This throws because 'giveMeException' service was not defined before
// accessing Thing from the container.
bottle.container.Thing; 
```

That being said, your use case makes total sense.  I think we can change bottle to also throw an exception when directly accessing an undefined service from the container when strict mode is enabled.

However, this would be a backwards incompatible change, i.e. there may be user-land code in strict mode that checks for a service being `undefined` for some reason (unlikely but possible).

So I'll need to include it in Bottle v2.0 (I have a small roadmap with some other, similarly breaking changes that I want to do for 2.0.  I'll put together my notes and add them to the Readme soon).

**Comment by akond** [comment]
I think it would be great.
Thank you very much.

**Comment by young-steveo** [comment]
@akond  So, I sat down to implement this, and suddenly realized that it can not be done without Proxies.  Since bottlejs supports IE9+ and other ECMAScript 5 compliant browsers, I don't think it can be done.

The reason should have been obvious to me from the beginning, but:  The container object is just an object.  With javascript, if you try to access an undefined property of an object, you always get `undefined`.

The magic behind the scenes of bottle is just `Object.defineProperties`.  So, when you define services, I'm just assigning getters/setters to the plain old javascript object container.

It's a chicken/egg problem:  Since you haven't told Bottle what property to set, it cannot set up a getter on the object.

Proxies solve this problem, and if you are in an environment that supports proxies, here's a snippet of code that you can use to shim this behavior:

```js
var bottle = new Bottle();
if (Bottle.config.strict) {
    bottle.container = new Proxy(bottle.container, {
        get : function (target, name) {
            if (name in target) {
                return target[name];
            }
            throw new Error(name + ' Service is undefined.');
        }
    });
}
```
