### ISSUE TITLE
Feature request: Support Symbol('..')

### ISSUE THREAD

**Issue by basickarl** [young-steveo/bottlejs#72]
Would be nice if it supported Symbols:

```
bottle.service(Symbol('RandomLib'), RandomLib);
```

Currently get the ```TypeError: fullname.split``` is not a function error.

**Comment by young-steveo** [comment]
@basickarl Thanks for the feature request!  I apologize for not getting back to you sooner, I've been on holiday.

Bottle currently supports ECMAScript 5 compliant browsers, including IE9, and Symbols were introduced in ECMAScript 6.  Also, Bottle does some string manipulation on the service keys in order to isolate nested keys (i.e. `"Parent.Child"`); since Symbols are immutable, this would cause a few problems with the implementation, I think.

If I ever make a version of bottle that supports ECMAScript 6, I'll probably do a rewrite of the core to use 6 under the hood, and I'll consider Symbols at that time.

**Comment by basickarl** [comment]
Thanks for the response and I understand :)
