### ISSUE TITLE
React Bindings

### ISSUE THREAD

**Issue by davidbarratt** [young-steveo/bottlejs#82]
Do you know if React Bindings exist for Bottle? Kind of like https://github.com/reactjs/react-redux ?

I imagine it working kind of like the way redux does, where you have  a "Provider" of sorts and then containers for children.

If this doesn't exist, would you want this to be part of this project or a separate project?

**Comment by young-steveo** [comment]
As far as I know, there's nothing out there.  I think adding it to this repo would depend on a handful of things.

* One primary point is that I don't use React; if these bindings need heavy maintenance, or need to evolve with new React versions/deprecations I might not be the man for the job.
* Not being familiar with React, I'm not sure how much code is involved in creating these bindings?  I imagine Redux is a fair bit more complicated than Bottle, but there's more code in the react-redux bindings repo than there is in the entire bottle repo.

So, if bindings require little maintenance, and the footprint is small, I could see including it in this repo.  Otherwise, I'd be happy to leave it up to someone else and link to those bindings in the Readme of this repo.

**Comment by young-steveo** [comment]
@davidbarratt  I'll close this for now.  If you're interested in maintaining react bindings, let me know.
