### ISSUE TITLE
Nested container infinite loop when trying to define a service using the nested container as the name.

### ISSUE THREAD

**Issue by AsyncWizard** [young-steveo/bottlejs#86]
Hi,

I've often been blocked when using nested containers.

Two examples in my mind:

The first, when, for organizational reasons, I wish to create a service child of a service:
```javascript
var Bottle = require('bottlejs');
var bottle = new Bottle;

bottle.service('DB', function () {
    this.DB = 'Hello from DB service';
});

bottle.service('DB.indexer', function () {
    this.AB = 'Hello from DB indexer';

});

console.log('DB service: ', bottle.container.DB); // Container instead of DB service
console.log('DB indexer service: ', bottle.container.DB.indexer); //Ok
```

The second example is **worse**. 
Imagine that I want to create a DB service with configuration value:
```javascript
var Bottle = require('bottlejs');
var bottle = new Bottle;

bottle.value('DB.config', {
    login: 'root',
    password: 'toor'
});

bottle.service('DB', function (config) {
    this.DB = 'Hello from DB service';
    this.conf = config;
}, 'DB.config');


console.log('DB service: ', bottle.container.DB);
console.log('DB config: ', bottle.container.DB.config);
```

Here the library is stuck in an infinite loop:
```
RangeError: Maximum call stack size exceeded
    at getNested (bottle.js:37:26)
    at Array.reduce (native)
    at Object.getNestedService (bottle.js:61:36)
    at Array.map (native)
    at GenericProvider.GenericFactory [as $get] (bottle.js:447:29)
    at Object.getService [as DB] (bottle.js:368:89)
    at getNested (bottle.js:37:26)
    at Array.reduce (native)
    at Object.getNestedService (bottle.js:61:36)
    at Array.map (native)
```
( For more informations, I use bottlejs v1.5.0 - node v7.1.0 )

It would be great if I could disable nesting by passing via `Bottle.config.nesting = false` for instance.

This could be done easily by replacing `parts = fullname.split('.')` by `parts = globalConfig.nesting ? fullname.split('.') : [fullname]`

Do you think this issue makes any sense ?

**Comment by young-steveo** [comment]
@morphose Hmm.  I'm thinking of a few scenarios to solve your problem.

I'll start with your second example.  It seems like you are trying to define a *property* of a service via the bottle api.  Something kind of like `Object.defineProperty`.  I wonder if you should instead use a decorator:

```js
bottle.service('DB', function () { });
bottle.decorator('DB', function(DB) {
    DB.config = {
        login : 'root',
        password : 'toor'
    };
    return DB;
});
```
As an aside, thanks for reporting the infinite loop; it is a bug that I should fix.  I think I've covered it for services, but not for constants and values.

For your first example, you're missing out on the benefit of injection.  I think the indexer should be injected into your DB service like:

```js
bottle.service('DBindexer', function () { });
bottle.service('DB', function (Indexer) {
    this.indexer = Indexer;
}, 'DBIndexer');
```
Granted, I have removed the dot notation from the indexer registration.

Finally, I don't think disabling the nested containers would work as you think.  For example, imagine some code like this:

```js
Bottle.config.nesting = false;
var bottle = Bottle.pop();
bottle.service('DB', function () { });
bottle.service('DB.indexer', function () { });

bottle.container.DB; // so far so good.
bottle.container.DB.indexer; // undefined
bottle.container['DB.indexer'] // found it.
```

Which is not exactly the expected behavior.

**Comment by morphose** [comment]
Thank you for your advices.
The main reason I used `bottle.value` is that I could easily deal with:
```javascript
bottle.value('DB.connection', await connection());
```
But you're right, I had in mind something close to symfony with eg `container.get('dotted.service')` (and promises are not the topic here).

I'll keep thinking about it in my project.

**Comment by young-steveo** [comment]
@morphose I see.  Since bottle is designed for injection during construction and your example is more like adding a public property to a service after construction, you could get away with something like this for now: 

```js
bottle.service('DB', function() { });
bottle.container.DB.connection = await connection();
```

**Comment by young-steveo** [comment]
The infinite loop problem is not due to what I thought at first.  After debugging your script, the loop occurs here:

```js
bottle.service('DB', function (config) { // defining DB
    this.DB = 'Hello from DB service';
    this.conf = config;
}, 'DB.config'); // Problem is here
```

You are attempting to inject something that is a child of `DB` before the `DB` service is created.  Dependencies are always resolved recursively before the service can be created.  So, while defining `DB` you try to inject `DB.property`, so bottle must lookup `DB` first (and loop indefinitely).
