### ISSUE TITLE
InstanceFactory with class

### ISSUE THREAD

**Issue by eskab** [young-steveo/bottlejs#94]
Is it possible to use `instanceFactory` with ES6 classes?
When I try to use it this way I get an error: `Uncaught TypeError: Cannot call a class as a function`

```
class A {
  constructor() {}

  foo() {}
}

class B {
  constructor(A) {
    const bar = A.instance();
    // here I get an error
  }
}

const bottle = new Bottle();
bottle.instanceFactory('A', A);
bottle.service('B', B, 'A');
```

**Comment by young-steveo** [comment]
`A.instance` is usually a function that returns an instance, but in your case `A.instance` becomes the class constructor itself.  So, something like this will work:

```js
class A {
  constructor() {}
  foo() {}
}
class B {
  constructor(A) {
    const bar = new A.instance; // new the constructor

    return bar;
  }
}

const bottle = new Bottle();
bottle.instanceFactory('A', A);
bottle.service('B', B, 'A');

console.log(bottle.container.B instanceof A); // true
```

If you build your entire app this way, then everything should be fine. 

However, you might run into maintenance trouble if you start mixing instance functions and instance constructors, because you won't know if you have to invoke `instance` or pass it to the `new` keyword unless you go back to the definition.

**Comment by eskab** [comment]
Okay, thank you for help :smile:
